#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libzip
Version  : 1.4.0
Release  : 12
URL      : https://nih.at/libzip/libzip-1.4.0.tar.xz
Source0  : https://nih.at/libzip/libzip-1.4.0.tar.xz
Summary  : library for handling zip archives
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libzip-bin
Requires: libzip-lib
Requires: libzip-doc
BuildRequires : bzip2-dev
BuildRequires : cmake
BuildRequires : zlib-dev
Patch1: export.patch

%description
This is libzip, a C library for reading, creating, and modifying zip
archives. Files can be added from data buffers, files, or compressed
data copied directly from other zip archives. Changes made without
closing the archive can be reverted. Decryption and encryption of
Winzip AES and decryption of legacy PKware encrypted files is
supported. The API is documented by man pages.

%package bin
Summary: bin components for the libzip package.
Group: Binaries

%description bin
bin components for the libzip package.


%package dev
Summary: dev components for the libzip package.
Group: Development
Requires: libzip-lib
Requires: libzip-bin
Provides: libzip-devel

%description dev
dev components for the libzip package.


%package doc
Summary: doc components for the libzip package.
Group: Documentation

%description doc
doc components for the libzip package.


%package lib
Summary: lib components for the libzip package.
Group: Libraries

%description lib
lib components for the libzip package.


%prep
%setup -q -n libzip-1.4.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1515023437
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1515023437
rm -rf %{buildroot}
pushd clr-build
%make_install
popd
## make_install_append content
mv %{buildroot}/usr/lib/libzip.so* %{buildroot}/usr/lib64/
## make_install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/zipcmp
/usr/bin/zipmerge
/usr/bin/ziptool

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/libzip.so
/usr/lib64/pkgconfig/libzip.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libzip.so.5
/usr/lib64/libzip.so.5.0
